//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMagazineProgramming.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public int IdAccount { get; set; }
        public int IdSCategory { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string Summary { get; set; }
        public string ContentView { get; set; }
        public Nullable<System.DateTime> DatePost { get; set; }
        public Nullable<bool> Active { get; set; }
        public int Viewed { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual SCategory SCategory { get; set; }
    }
}
